Removed the mount material; Adjusted 1c geometry for the overlap sensors.
EMPHATICSoft/emphaticsoft pull request #149
Opened 2023-12-16 18:56 UTC by linyan-w

2024-01-06 00:43 UTC, jonpaley requested changes
If the mounts have been removed, then we need to adapt the classes in the Geometry.  Eg, the local-to-global coordinate transform took into account the fact that the sensors were attached to the mounts, so we went from strip to sensor to mount to station to global position.  Now I think we need to remove the "to mount" step, right?  This should be done and tested before merging into main.

2024-01-06 01:43 UTC, linyan-w commented
This PR removes the mount material. It does not remove the mount volume.
This is different from the solution we discussed during the CM.
The argument for this PR is the following:
The mount volume does not introduce conflict. It is the mount material that
introduces conflicts when adding more degrees of freedom to the SSD
sensors, therefore we only need to remove the material. The geometry does
not need to change.
As for tests, I tested it with the nominal setup and it worked. I have not
yet tested it with the setting where two sensors independently rotate (I
don't know how to yet).

On Fri, Jan 5, 2024 at 6:43 PM Jon Paley ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> If the mounts have been removed, then we need to adapt the classes in the
> Geometry. Eg, the local-to-global coordinate transform took into account
> the fact that the sensors were attached to the mounts, so we went from
> strip to sensor to mount to station to global position. Now I think we need
> to remove the "to mount" step, right? This should be done and tested before
> merging into main.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/EMPHATICSoft/emphaticsoft/pull/149#pullrequestreview-1807124641>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMXBSRHYOKHLIAOBKROTI63YNCM4DAVCNFSM6AAAAABAXYSHQSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQMBXGEZDINRUGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-01-08 01:46 UTC, jonpaley commented
Ah, ok, sounds fine then!

2024-01-08 01:47 UTC, jonpaley approved these changes

2024-01-23 20:06 UTC, merged